global using System.Runtime.InteropServices;
global using System;
global using System.Collections.Generic;
global using System.Linq;
global using Dalamud.Plugin;
global using Dalamud.Bindings.ImGui;
global using ECommons.DalamudServices;
global using Dalamud.Interface;
global using Dalamud.Interface.Colors;
global using ECommons.Logging;
global using ECommons;
global using static ECommons.GenericHelpers;
global using ECommons.ImGuiMethods;
global using ECommons.SimpleGui;
global using ECommons.Configuration;
global using ECommons.Automation.LegacyTaskManager;
global using ECommons.Throttlers;
global using ECommons.Automation;
global using Callback = ECommons.Automation.Callback;
global using Dalamud.Game.ClientState.Conditions;
global using static VendingMachine.Plugin;
